version: 1.0.{build}
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: >-
      dotnet restore

install:
  - sh: sudo apt install ghostscript -y
build:
  project: PdfToPdfA1b.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PdfToPdfA1b.*.nupkg'

deploy:
  - provider: GitHub
    auth_token:
      secure: cm3wTP8rsFspZYpKCb63n0p4vRkEeZ+zXkEe/YxwRFW9D9m0yp2u0NdFnieLCWs3
    prerelease: true
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
    on:
      branch: master
